### PR TITLE
Latest updates

### PR DESCRIPTION
**Pull request by robahtou**
* mobile menu dropdown transition
* Top places is responsive from two columns (mobile) to two rows (desktop)
* server actions functional
* postgres integration for server actions

### CODE REVIEW

**Comment by rgreinho** [comment]
@robahtou the package updates conflict 📦

**Comment by robahtou** [comment]
@rgreinho should be ok now

**Review by rgreinho — APPROVED** [review]
👍

**Comment by robahtou** [comment]
🎉 🍰

**Pull request merged**
